name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build the application
      run: npm run build
    
    - name: Run tests
      run: npm test

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reactapp4ggm4amal' # Replace YOUR_APP_NAME with  your Azure App Service name
        publish-profile: ${{ secrets.appsec1 }} # Store publish profile in GitHub secrets
        package: '.' # This should be the root of your app or the output directory of build command



